apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
    - name: http # for management console
      port: 8161
      nodePort: 30010

    - name: endpoint # for sending and receiving messages
      port: 61616
  type: NodePort